[package]
name = "pegasus_graph"
version = "0.1.0"
authors = ["chenqiang.mcq <chenqiang.mcq@alibaba-inc.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.0"
nohash-hasher = "0.2.0"
crossbeam-utils = "0.8.7"
#snap = "1"
rand = "0.8.3"
memmap = "0.7.0"
ahash = "0.7.2"
lazy_static = "1.3.0"
pegasus_common = { path = "../common" }

[dev-dependencies]
structopt = "0.3"
