[package]
name = "graph_proxy"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
lazy_static = "1.3.0"
graph_store = {path = "../../../graph_store"}
maxgraph-store = {path = "../../../../interactive_engine/executor/store"}
dyn_type = { path = "../../../dyn_type" }
ir_common = {path = "../common"}
pegasus = { path = "../../../engine/pegasus/pegasus" }
pegasus_common = { path = "../../../engine/pegasus/common" }
pegasus_network = { path = "../../../engine/pegasus/network" }
pegasus_server = { path = "../../../engine/pegasus/server" }
runtime = { path="../runtime" }

[features]
default = []
proto_inplace = ["ir_common/proto_inplace"]
