[package]
name = "pegasus_network"
version = "0.1.0"
authors = ["chenqiang.mcq <chenqiang.mcq@alibaba-inc.com>"]
edition = "2018"

[dependencies]
log = "0.4"
lazy_static = "1.3.0"
pegasus_common = { path = "../common" }
crossbeam-channel = "0.4.4"
crossbeam-utils = "0.7.0"
crossbeam-queue = "0.1"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
enum_dispatch = "0.3"

[dev-dependencies]
structopt = { version = "0.3", default-features = false }

[features]
benchmark = []



