apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "graphscope.fullname" . }}-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ["apps", "extensions", ""]
  resources: ["configmaps", "deployments", "deployments/status", "endpoints", "events", "pods", "pods/log", "pods/exec", "pods/status", "services", "replicasets"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "graphscope.fullname" . }}-role-binding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "graphscope.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
