apiVersion: v1
kind: Service
metadata:
  name: {{ include "graphscope-store.frontend.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels: {{- include "graphscope-store.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: service-port
      port: {{ .Values.frontend.service.servicePort }}
      targetPort: service-port
    - name: port
      port: {{ .Values.frontend.service.port }}
      targetPort: port
    - name: gaia-rpc
      port: {{ .Values.frontend.service.gaiaRpc }}
      targetPort: gaia-rpc
    - name: gaia-engine
      port: {{ .Values.frontend.service.gaiaEngine }}
      targetPort: gaia-engine
  selector: {{- include "graphscope-store.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
