apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-store-headless" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: store
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:q
    - name: engine
      port: {{ .Values.store.service.engine }}
      targetPort: engine
    - name: gaia-rpc
      port: {{ .Values.store.service.gaiaRpc }}
      targetPort: gaia-rpc
    - name: gaia-engine
      port: {{ .Values.store.service.gaiaEngine }}
      targetPort: gaia-engine
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: store
