[package]
name = "ir_core"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
dyn_type = {path = "../../../dyn_type"}
env_logger = "0.9.0"
ir_common = {path = "../common"}
runtime = {path="../runtime"}
lazy_static = "1.3.0"
log = "0.4"
pegasus_server = {path = "../../../engine/pegasus/server"}
pegasus = {path = "../../../engine/pegasus/pegasus"}
prost = "0.9"
serde = "1.0"
serde_json = "1.0"
vec_map = { version = "0.8.2", features = ["serde"] }

[features]
default = []
proto_inplace = ["ir_common/proto_inplace"]

