[package]
name = "ffi"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
ir_common = {path = "../common"}
dyn_type = { path = "../../../dyn_type" }
libc = "0.2"
byteorder = "1.3.1"
itertools = "0.7.8"
maxgraph-store = {path = "../../../../interactive_engine/executor/store"}
maxgraph-runtime = {path = "../../../../interactive_engine/executor/runtime"}

[build-dependencies]
cmake = "0.1"
