[package]
name = "v6d_ffi"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
ir_common = {path = "../common"}
dyn_type = { path = "../../../dyn_type" }
libc = "0.2"
byteorder = "1.3.1"
itertools = "0.7.8"
global_query = {path = "../../../../interactive_engine/executor/global_query"}

[build-dependencies]
cmake = "0.1"

[features]
default = []
with_v6d = []
