annotations:
  category: Database
apiVersion: v2
appVersion: 0.8.0
description: Chart to create a GraphScope Store cluster
home: https://graphscope.io
keywords:
  - GraphScope
  - database
  - cluster
name: graphscope-store
sources:
  - https://github.com/alibaba/GraphScope/tree/main/interactive_engine/src/v2/src/main
version: 0.8.0

dependencies:
  - condition: kafka.enabled
    name: kafka
    version: 12.17.6
    repository: https://charts.bitnami.com/bitnami
