annotations:
  category: Database
  licenses: Apache-2.0
apiVersion: v2
appVersion: 3.4.0
description: GraphScope Store is a disk-based row-oriented multi-versioned persistent graph store
  and can be used to as a graph database service. GraphScope Store supports the popular
  graph query language -- Apache TinkerPop Gremlin. It's also named groot.
home: https://graphscope.io
icon: https://graphscope.io/assets/images/graphscope-logo.svg
keywords:
  - GraphScope
  - Groot
  - database
  - cluster
name: graphscope-store
sources:
  - https://github.com/alibaba/GraphScope/tree/main/interactive_engine
maintainers:
- name: GraphScope
  url: https://github.com/alibaba/graphscope
version: 0.28.0

dependencies:
- condition: kafka.enabled
  name: kafka
  repository: https://charts.bitnami.com/bitnami
  version: "20.0.6"
- name: common
  repository: https://charts.bitnami.com/bitnami
  version: 2.x.x
