[package]
name = "groot-store"
version = "0.1.0"
authors = ["勤远 <wubin.cwb@alibaba-inc.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
byteorder = "1.4.3"
log = "0.4"
protobuf = { version = "2.27", features = ["with-bytes"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
structopt = "0.3"
tempfile = "3"
crossbeam-epoch = "0.7"
rust-ini = "0.13"
libc = "0.2"
log4rs = "1.2"
grpcio = "0.10"
grpcio-sys = { version = "0.10", features = ["openssl-vendored"] }
# deactivation of bzip2 due to https://github.com/rust-rocksdb/rust-rocksdb/issues/609
# rocksdb = { version = "0.19.0", features = ["snappy", "lz4", "zstd", "zlib"], default-features = false }
dyn_type = { path = "../../common/dyn_type" }

[build-dependencies]
protoc-grpcio = "3.0"

[dependencies.rocksdb]
git = "https://github.com/GoldenLeaves/rust-rocksdb.git"
rev = "082dfcfbb4b51e61d1c01672951b84cb464601e2"

[dev-dependencies]
rand = "0.8.5"

[[bin]]
name = "write_bench"
