[package]
name = "maxgraph-runtime"
version = "0.1.0"
authors = ["maxgraph@alibaba-inc.com"]

[dependencies]
abomonation = "0.7"
abomonation_derive = "0.3"
bincode = "1.0.1"
byteorder = "1.3.1"
crossbeam-channel = "0.4.4"
crossbeam-queue = "0.1"
tokio-sync = "0.1.6"
tokio = "0.1.6"
tokio-core = "0.1.6"
futures = "0.1.25"
futures-cpupool = "0.1.8"
getopts = "0.2.14"
grpcio = "=0.4.1"
quote = "=1.0.1"
itertools = "0.7.8"
lazy_static = "1.2.0"
log = "0.3"
log4rs = "0.8.0"
maxgraph-common = { path = "../../rust-common" }
maxgraph-store = { path = "../store" }
maxgraph-server = { path = "../server" }
protobuf = { version = "~2.0", features = ["with-bytes"] }
rand = "0.7.3"
regex = "1"
serde = "1.0.72"
serde_derive = "1.0.72"
serde_json = "1.0.3"
structopt = "0.2"
zookeeper = { git = "https://github.com/bonifaido/rust-zookeeper.git", rev = "fd222dd" }
lru_time_cache = "0.8.0"
pegasus = { path = "../Pegasus" }
libc = "0.2"

[dev-dependencies]
env_logger = "0.6"

[build-dependencies]
cmake = "0.1"
