[package]
name = "global_query"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
itertools = "0.7.8"
byteorder = "1.3.1"
serde = "1.0.72"
maxgraph-store = { path = "../store" }