name: GraphScope GAE CI (Dummy)

on:
  pull_request:
    branches:
      - main
    paths:
      - '**'
      - '!analytical_engine/**'
      - '!.github/workflows/gae.yml'
      - '!coordinator/gscoordinator/template/CMakeLists.template' # to verify whether java app can be successfully built when CMakeLists.template changes.
      - 'analytical_engine/**.md'

concurrency:
  group: ${{ github.repository }}-${{ github.event.number || github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-gae:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'alibaba/GraphScope' }}
    steps:
    - run: 'echo "No action required" '
