name: GraphScope GAIA CI

on:
  # Trigger the workflow on push or pull request, but only for the main branch
  push:
    branches:
      - main
    paths:
      - 'research/**'
      - '.github/workflows/gaia.yml'
      - '!research/**.md'
  pull_request:
    branches:
      - main
    paths:
      - 'research/**'
      - '.github/workflows/gaia.yml'
      - '!research/**.md'

jobs:
  gaia-test:
    runs-on: [self-hosted, manylinux2014]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ~/.cache/sccache
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install Dependencies
      run: |
        # install rdkafka
        sudo yum install -y librdkafka-devel

        export SCCACHE_DIR=~/.cache/sccache
        export RUSTC_WRAPPER=/usr/local/bin/sccache
        sccache --start-server

        # install cppkafka
        git clone -b 0.4.0 --single-branch --depth=1 \
            https://github.com/mfontanini/cppkafka.git /tmp/cppkafka && \
          cd /tmp/cppkafka && git submodule update --init && \
          mkdir -p build && cd build && \
          cmake .. && make -j && sudo make install && \
          rm -fr /tmp/cppkafka

    - name: Build Ir on Experimental Store
      run: |
        source ${HOME}/.bashrc
        cd ${GITHUB_WORKSPACE}/research/query_service/ir/compiler
        make build

    - name: Build Ir on Groot Store
      run: |
        source ${HOME}/.bashrc
        cd ${GITHUB_WORKSPACE}/interactive_engine
        mvn clean install -DskipTests -Pv2

    - name: Ir Unit Test
      run: |
        source ${HOME}/.bashrc
        cd ${GITHUB_WORKSPACE}/research/query_service/ir/compiler && make test

    - name: Ir Integration Test on Experimental Store
      run: |
        source ${HOME}/.bashrc
        cd ${GITHUB_WORKSPACE}/research/query_service/ir/compiler && ./ir_exprimental_ci.sh

    - name: Ir Integration Test on Groot Store
      run: |
        source ${HOME}/.bashrc
        cd ${GITHUB_WORKSPACE}/interactive_engine/ir-adaptor && ./ir_groot_ci.sh

