name: GraphScope GAIA CI

on:
  # Trigger the workflow on push or pull request, but only for the main branch
  push:
    branches:
      - main
    paths:
      - 'research/**'
      - '.github/workflows/gaia.yml'
      - '!research/**.md'
  pull_request:
    branches:
      - main
    paths:
      - 'research/**'
      - '.github/workflows/gaia.yml'
      - '!research/**.md'

jobs:
  gaia-test:
    runs-on: ubuntu20.04
    container:
      image: registry.cn-hongkong.aliyuncs.com/graphscope/graphscope-vineyard:v0.3.21
    defaults:
      run:
        shell: bash --noprofile --norc -eo pipefail {0}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Dependencies
      run: |
        # install cargo cause github change $HOME to /github/home, so we can't use
        # `source ~/.bashrc` or `source ${HOME}/.bashrc` to find cargo command.
        sudo chown -R $(id -u):$(id -g) ${HOME}
        sudo chmod -R a+wrx ${HOME} ${GITHUB_WORKSPACE}
        wget --no-verbose https://golang.org/dl/go1.15.5.linux-amd64.tar.gz
        sudo tar -C /usr/local -xzf go1.15.5.linux-amd64.tar.gz
        curl -sf -L https://static.rust-lang.org/rustup.sh | sh -s -- -y --profile minimal --default-toolchain 1.54.0
        echo "source ~/.cargo/env" >> ~/.bashrc
        source ${HOME}/.bashrc
        rustup component add rustfmt
        # install rdkafka
        sudo yum install -y librdkafka-devel
        # install cppkafka
        git clone -b 0.4.0 --single-branch --depth=1 \
            https://github.com/mfontanini/cppkafka.git /tmp/cppkafka && \
          cd /tmp/cppkafka && git submodule update --init && \
          mkdir -p build && cd build && \
          cmake .. && make -j && sudo make install && \
          rm -fr /tmp/cppkafka

    - name: Build Ir on Experimental Store
      run: |
        source ${HOME}/.bashrc
        cd ${GITHUB_WORKSPACE}/research/query_service/ir/compiler
        make build

    - name: Build Ir on Groot Store
      run: |
        source ${HOME}/.bashrc
        cd ${GITHUB_WORKSPACE}/interactive_engine
        mvn clean install -DskipTests -Pv2

    - name: Ir Unit Test
      run: |
        source ${HOME}/.bashrc
        cd ${GITHUB_WORKSPACE}/research/query_service/ir/compiler && make test

    - name: Ir Integration Test on Experimental Store
      run: |
        source ${HOME}/.bashrc
        cd ${GITHUB_WORKSPACE}/research/query_service/ir/compiler && ./ir_exprimental_ci.sh

    - name: Ir Integration Test on Groot Store
      run: |
        source ${HOME}/.bashrc
        cd ${GITHUB_WORKSPACE}/interactive_engine/ir-adaptor && ./ir_groot_ci.sh

